FROM nginx:alpine

COPY accounting.html /usr/share/nginx/html/index.html
COPY accounting.css /usr/share/nginx/html/accounting.css
COPY accounting.js /usr/share/nginx/html/accounting.js
COPY filters.js /usr/share/nginx/html/filters.js
COPY translations.js /usr/share/nginx/html/translations.js

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]