services:
  backend:
    build: ./backend
    container_name: backend_acc_app
    ports:
      - "5001:5001"
    env_file:
      - ./backend/.env
    networks:
      - app-network

  frontend:
    build: ./frontend
    container_name: frontend_acc_app
    ports:
      - "5500:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
